version: "3"

services:
  api:
    build: .
    container_name: alpha_investimentos_api
    command: bash -c 'while !</dev/tcp/db/3306; do sleep 1; done; npm start'
    volumes:
      - .:/usr/app/
      - /usr/app/node_modules
    depends_on:
      - db
    ports:
      - 3000:3000
    environment:
      MYSQL_USER: root
      MYSQL_PASSWORD: password
      MYSQL_HOST: db
      PORT: '3000'

  db:
    container_name: alpha_investimentos_api_db
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - 3306:3306
    volumes:
      - "./scripts/alpha_investimentos_api_db.sql:/docker-entrypoint-initdb.d/1.sql"
